# -*- coding: utf-8 -*-
"""imposter_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIOwVc-l-eFVsMlzvnvcmRDcbx8q-95m
"""

print("Welcome to the Imposter Game!")

no_of_player = int(input("Enter the number of players: "))

players_list = []
choice = input("Do you wish to add customised player names? (Y/N)").lower()
if choice == "n":
  for i in range(no_of_player):
    name = f"Player {i+1}"
    players_list.append(name)
else:
  for i in range(no_of_player):
    name = input(f"Enter the name of Player{i+1}")
    players_list.append(name)

for player in players_list:
  print(player)


# no duplicate restriction should be there as names can be same

import random
words = [
    "apple", "football", "doctor", "school", "river",
    "computer", "music", "coffee", "beach", "movie",
    "family", "festival", "train", "mountain", "phone"
]

secret_word = random.choice(words)
imposter = random.choice(players_list)
# index = players_list.index(imposter)
# players_list[index] = "imposter"
# print(secret_word,imposter)
# players_list

from IPython.display import clear_output

total_players = len(players_list)
possible_game_starters = [p for p in players_list if p != imposter]
game_starter = random.choice(possible_game_starters)

for index,player in enumerate(players_list):
  clear_output(wait=True)
  input("Press enter to see your role")
  # if player == "imposter":
  if player == imposter:
    print("Shh! you are the Imposter! try to mix in with others..")
  else:
    print(f"The secret word is {secret_word}")

  if index != total_players -1:
    clear_output(wait=True)
    input("Press enter and pass the device to the next player!")
  else:
    input("Press enter to start")
    clear_output(wait=True)
    print("Imposter is created")
    print(f"Everyone has to say one word related to the secret word")
    print(f"{game_starter} will start the game!")
    print(f"Let the game begin!!")

input("Press enter when you want to reveal the imposter")
clear_output(wait=True)
print(f"The imposter is {imposter}")

